---
title: Letters To Summer
description: Two friends sharing the things they're reading, watching, listening to, and enjoying. In your inbox every other Thursday.
url: https://letterstosummer.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
repository: jilliangmeehan/letters-to-summer
