---
title: Letters To Summer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
repository: jilliangmeehan/letters-to-summer
